using Duets.Pad.Rendering;

namespace Duets.Pad.Timeline;

/// <summary>
/// A single structured history entry in a DuetsPad Timeline.
/// </summary>
/// <param name="Id">The non-negative entry identifier.</param>
/// <param name="Reason">The event category that produced the entry.</param>
/// <param name="Body">The terminal render tree displayed for the entry.</param>
/// <param name="Timestamp">The time at which the entry was created.</param>
public sealed record TimelineEntry(
    long Id,
    string Reason,
    ITerminalRenderNode Body,
    DateTimeOffset Timestamp
)
{
    /// <summary>
    /// Gets the non-negative entry identifier. Identifiers generated by
    /// <see cref="TimelineState.Append"/> increase until <see cref="TimelineState.Clear"/> starts a
    /// new sequence at zero; <see cref="TimelineState.Trim"/> preserves the current sequence.
    /// </summary>
    public long Id { get; } = Id >= 0 ? Id : throw new ArgumentOutOfRangeException(nameof(Id));

    /// <summary>Gets the event category that produced the entry.</summary>
    public string Reason { get; } =
        !string.IsNullOrWhiteSpace(Reason)
            ? Reason
            : throw new ArgumentException("Timeline entry reason cannot be empty.", nameof(Reason));

    /// <summary>Gets the terminal render tree displayed for the entry.</summary>
    public ITerminalRenderNode Body { get; } =
        Body ?? throw new ArgumentNullException(nameof(Body));

    /// <summary>Gets the time at which the entry was created.</summary>
    public DateTimeOffset Timestamp { get; } = Timestamp;
}
